# Generated by Django 2.1.5 on 2019-02-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_auto_20190208_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total',
            new_name='total_invoice',
        ),
    ]
