# Generated by Django 2.1.5 on 2019-02-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_auto_20190208_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
    ]
