# Generated by Django 2.1.5 on 2019-02-11 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_product_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Invoice'),
        ),
    ]
