# Generated by Django 2.1.5 on 2019-02-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_auto_20190211_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='invoice',
        ),
        migrations.AddField(
            model_name='product',
            name='relational_invoices',
            field=models.ManyToManyField(to='product_app.Invoice'),
        ),
    ]
