# Generated by Django 2.1.5 on 2019-02-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0010_invoice_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_product',
            old_name='cantidad',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='relational_invoices',
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(through='product_app.Invoice_Product', to='product_app.Product'),
        ),
    ]
